### ISSUE TITLE
Illegal Double declaration

### ISSUE THREAD

**Issue by Catman155** [ewilken/hap-rs#16]
in the file `"src/characteristic/mod.rs"` there is an double declaration of `Deserialize`. Somehow this compiles for me on Rust version 1.35. But this shouldn't be legal at all as far as I know.

**Comment by Catman155** [comment]
according to[ this reddit forum](https://www.reddit.com/r/rust/comments/a8ykj8/til_you_dont_need_serde_derive_when_using_the/) the derive macro's/traits can be added with the same import statement

**Comment by Catman155** [comment]
Issue shows itself easily when using `reqwest`.

**Comment by ewilken** [comment]
Thank you! :) `v0.0.7` with a fix is published to crates.io now.
