### ISSUE TITLE
How to use this crate with RGB Lightbulb?

### ISSUE THREAD

**Issue by AlexeySemigradsky** [ewilken/hap-rs#33]
I found generated characteristics for  hue, saturation and brightness, but couldn't find examples on how to use that.

**Comment by fzzr-** [comment]
@AlexeySemigradsky check out [optional fields there](https://docs.rs/hap/0.1.0-pre.6/hap/service/lightbulb/struct.LightbulbService.html). 👋

**Comment by ewilken** [comment]
You're right about this not being ergonomic. I will evaluate having optional characteristics generated as `Some` by default. See #43.

**Comment by ewilken** [comment]
Lightbulb accessories are now generated as RGB by default. See the `lightbulb` example.
