### ISSUE TITLE
Bump Tokio to 1.0

### ISSUE THREAD

**Issue by bahlo** [ewilken/hap-rs#41]
Tokio released `v1.0` recently and lots of libraries have switched to it. I'm trying to use this with a different library that uses Tokio 1.0 already and that obviously doesn't work.

Can we bump Tokio?

Thanks

**Comment by ewilken** [comment]
Yes! I'm already on it. Hoped to finish it way earlier, but the change should be out in the next days.

**Comment by bahlo** [comment]
Sounds awesome, thanks for the update!

**Comment by ewilken** [comment]
Still WIP, the progress is tracked [here](https://github.com/ewilken/hap-rs/tree/tokio-1). The pairing process is currently erroring and I'm still hunting the bug.

**Comment by ewilken** [comment]
`v0.1.0-pre.7` is out! 🎉
