### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by laibulle** [ewilken/hap-rs#5]
Hello,  

I am quite interested in your HAP implementation for my home automation server. But for now, I know nothing about HAP and I am quite a newbie with Rust. 

So before spending a lot of time understanding the behaviour of the the protocol, I would like to know if your library is at least partially functional. Do you have some sample code to help people using the library?

Thanks a lot for your work.

**Comment by ewilken** [comment]
Thanks for your interest! :)

The library is already fully functional except for camera streams.

Gonna add proper docs, examples and a readme explaining the core concepts of the HAP as well as this particular implementation tomorrow and publish the project to crates.io soon.

If you want to dive deeper into how the protocol works you can obtain the full non-commercial specification from [Apple's HomeKit developer page](https://developer.apple.com/homekit/). But this library really should abstract quite a lot of the complex parts of it away.

**Comment by laibulle** [comment]
Thanks for the example.

Is there a way to dynamically  add devices or should I restart IpTransport every time I add device.

**Comment by ewilken** [comment]
So I implemented [`add_accessory()`](https://github.com/ewilken/hap-rs/blob/master/src/transport/ip.rs#L165) and [`remove_accessory()`](https://github.com/ewilken/hap-rs/blob/master/src/transport/ip.rs#L169) methods to add/remove Accessories dynamically. An example is provided in the readme. Let me know if this helps and please feel free to open more specific issues if you run into any quirks or missing features.

**Comment by laibulle** [comment]
Thank you.

Do you have an idea of how I could start the server in a different thread ?

**Comment by ewilken** [comment]
With v0.0.4, the HAP server is now thread-safe. So you can do stuff like this now:
```rust
let mut ip_transport = IpTransport::new(Config::default()).unwrap();
ip_transport
    .add_accessory(outlet::new(Information::default()).unwrap())
    .unwrap();

std::thread::spawn(move || {
    ip_transport.start().unwrap();
});
```
It's still lacking a convenient API for inter-thread operations on the server tho. I'm thinking of overhauling this crate's public API for v0.1 into something like what [Actix](https://github.com/actix/actix) does (or just integrating Actix).

Closing this for now, as there's no concrete actionability left in this issue.
