### ISSUE TITLE
Creating custom characteristics, services & accessories

### ISSUE THREAD

**Issue by ewilken** [ewilken/hap-rs#61]
We need to validate it being possible with the currently exported API and add an example for it.

**Comment by gbaranski** [comment]
> We need to validate it being possible with the currently exported API and add an example for it.

Hi, what's the status of this issue?

I'm trying to build an accessory that is a sensor which does implements both `temperature` and `humidity` and I'm not sure if that's possible.

**Comment by ewilken** [comment]
The progress of the implementation is tracked [here](https://github.com/ewilken/hap-rs/pull/62). The work on it slowed down a little over the last weeks due to lack of time, but I'm going to try and get it done soon.

> I'm trying to build an accessory that is a sensor which does implements both `temperature` and `humidity` and I'm not sure if that's possible.

That's a good question! From a pure HomeKit data model perspective this should be totally doable as an accessory exposing two different sensor services. I'm not sure if an iOS controller is going to accept that as a valid accessory, but I guess it should. Will add an example case testing it out!

**Comment by ewilken** [comment]
It's indeed working! [There](https://github.com/ewilken/hap-rs/blob/main/examples/custom_multi_sensor.rs) you go. :)

```
cargo run --example custom_multi_sensor
```

**Comment by gbaranski** [comment]
> It's indeed working! [There](https://github.com/ewilken/hap-rs/blob/main/examples/custom_multi_sensor.rs) you go. :)
> 
> ```
> cargo run --example custom_multi_sensor
> ```

awesome, thank you very much.
