### ISSUE TITLE
Status of this crate

### ISSUE THREAD

**Issue by somehowchris** [ewilken/hap-rs#65]
Hey 👋🏻 

As there is no action since mid last year, do you plan on maintaining this crate?

**Comment by ewilken** [comment]
Hi!

Yes, definitely!

There was action after mid last year btw. 🙂

I'm very happy about contributions, being a little time-constrained myself these days. There's some labeled issues that might be a good starting point for helping out.

Anything specific you're interested in?

**Comment by somehowchris** [comment]
Sry, end of last year 😅 

My primary points of interest are #40 and keeping this such as dependencies updated

**Comment by simlay** [comment]
Just to show interest, I've played around with getting #47 off an on a while ago. I should pick that work back up.

**Comment by somehowchris** [comment]
My final goal would be to have some small boards like `arduino uno` to be stand alone accessories, does this sound out of this word?

Also looked into `homebridge` and it would be lovely to port something like it to rust, `hap-rs` seems like to crate to use for protocol abstraction
