### ISSUE TITLE
FnMut instead of Fn for on_update_async

### ISSUE THREAD

**Issue by soundprojects** [ewilken/hap-rs#67]
Is it possible for the `on_update_async()` function of characteristics to allow for functions that can change a variable outside of the function? I am currently trying to use these functions to change something when a characteristic changes but because it is Fn it doesn't allow me to 🙂

**Comment by ewilken** [comment]
Sure, good point, sounds worth looking into. Thanks for raising it! 🙂

Happy to accept a PR changing it if you feel like just changing it yourself. Otherwise I can look into it too.
